spring:
  application:
    name: cafe
  datasource:
    url: jdbc:mysql://localhost:3306/cafes?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev
##  메일
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: teamssal0515@gmail.com
#    password:
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#          auth: true

#logging:
#  level:
#    org.hibernate.SQL: debug

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZon: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: Hi:imCafe

